### ISSUE TITLE
Ajout du chauffage

### ISSUE THREAD

**Issue by florianpanchout** [datagir/monconvertisseurco2#105]
Un des termes de recherche les plus fréquent est chauffage. On peut ajouter le chauffage à partir de la Base Carbone (via https://bilans-ges.ademe.fr/documentation/UPLOAD_DOC_FR/index.htm?chauffage.htm plus FE de chacun des combustibles). 

Dans l'ancienne version de MCC, on affichait l'équivalent "Jour de chauffage gaz", mais la valeur au jour est juste la moyenne à l'année divisée par 365 donc trompeuse.

Je propose d'afficher en année de chauffage plutôt. Est ce que ça vous va ?

**Comment by Clem-mrtn** [comment]
Oui ça me parait bien ! D'autant qu'on ne chauffe pas pareil toute l'année, donc par jour c'est trompeur effectivement.
Lissé sur l'année ça le fait je pense 👍

**Comment by Clem-mrtn** [comment]
https://chauffage--mcc-v2.netlify.app/categories/chauffage/

**Comment by florianpanchout** [comment]
C'est en prod

**Comment by Clem-mrtn** [comment]
Trop bien l'infographie chauffage 👍

**Comment by florianpanchout** [comment]
Je ré-ouvre cette issue : est ce que ce ne serait pas plus logique d'afficher la valeur au m2 (plutôt que d'utiliser 80m2 ?). J'ai l'impression que ça correspondrais plus à l'usage (et c'est plus cohérent avec le reste du site ou les FE sont à l'unité)

**Comment by florianpanchout** [comment]
Done

**Comment by martinregner** [comment]
Retour pertinent d'un utilisateur sur le chauffage en m2

> Il est très bien mais il me semble qu'il y a une erreur de conversion pour l'année de chauffage de gaz pour une maison (actuellement 38 kg de C02, ce qui est bien trop faible).
> Cela a induit une erreur dans cet article 
> https://actu.fr/nouvelle-aquitaine/bordeaux_33063/quel-est-ce-yacht-bleu-de-pres-de-100-metres-amarre-au-port-de-bordeaux_53627849.html

Même si ce n'est pas une erreur de notre côté, cela veut dire que ce n'est pas assez visible que c'est pour 1m2.
Serait-il possible de mettre plutôt un sélecteur dessus façon MIT, en le positionnant à 80m2 par ex. par défaut ?

**Comment by florianpanchout** [comment]
Yes ça rejoint cette issue https://github.com/datagir/monconvertisseurco2/issues/127

**Comment by florianpanchout** [comment]
J'ai modifié l'affichage tuile pour qu'il prenne un multiplicateur en compte (113m2 pour une maison, 63m2 pour un appartement via @Clemog ici :https://github.com/datagir/monconvertisseurco2/issues/127#issuecomment-1241680460)

C'est ici : https://unit-display--monconvertisseurco2.netlify.app/co2e

**Comment by florianpanchout** [comment]
C'est en prod
