### ISSUE TITLE
Faire varier le FE de l'avion selon la distance

### ISSUE THREAD

**Issue by florianpanchout** [datagir/monconvertisseurco2#115]
Sur MIT on a 4 FE possibles pour l'avion (< 1000km, < 2000km, <3500km et >3500km). On en a repris qu'un seul pour l'instant sur MCC. 

Pour [la page catégorie](https://nextjs-monconvertisseurco2.netlify.app/categories/transport) c'est plutôt simple, on affiche la bonne valeur en fonction du nombre de km choisi, comme sur MIT.

Mais comment l'afficher sur [la page équivalent de l'avion](https://nextjs-monconvertisseurco2.netlify.app/categories/transport/avion) ? Je propose de prendre une seule valeur et d'afficher les autres via une infographie (un peu comme celle du smartphone.

Une autre option serait d'avoir 4 pages différentes, mais je pense que ça complexifierait inutilement le site

**Comment by Clem-mrtn** [comment]
> Mais comment l'afficher sur [la page équivalent de l'avion](https://nextjs-monconvertisseurco2.netlify.app/categories/transport/avion) ? Je propose de prendre une seule valeur et d'afficher les autres via une infographie (un peu comme celle du smartphone. 

Ok mais je ne vois pas très bien comment ça se représenterait : aujourd'hui on a une infographie pour "1Km en avion équivaut à.." 
Comment on représenterait les 3 autres FE ? On ferait une info 1000Km en avion, une info 2000 Km etc. ?

>Une autre option serait d'avoir 4 pages différentes, mais je pense que ça complexifierait inutilement le site

Oui je suis tout à fait d'accord

**Comment by florianpanchout** [comment]
> Ok mais je ne vois pas très bien comment ça se représenterait : aujourd'hui on a une infographie pour "1Km en avion équivaut à.."

J'imaginais une infographie avec une structure comme celle ci : 
![smartphone (35)](https://user-images.githubusercontent.com/8115933/187487879-5bbd5175-8d63-4d29-b364-fa9e951ed1cb.png)

**Comment by Clem-mrtn** [comment]
Ok carrément ! 👍

**Comment by martinregner** [comment]
Vu en point produit : ajouter des précisions dans le libellé "Avion **(...)**".
Je propose le nombre de sièges :
- 500 à 1 000 km, 101 à 220 sièges
- 1 000 à 2 000 km, 101 à 220 sièges
- 2 000 à 3 500 km, >220 sièges
- au delà de 3 500 km, >220 sièges

**Comment by florianpanchout** [comment]
Donc quelle libellé afficher ? `Court courrier` / `Moyen courrier` / `Long courrier` ?

**Comment by martinregner** [comment]
Voici ce que j'ai trouvé sur le forum de la Base Carbone : [FE aériens (valeurs moyennes) : définition de court / moyen / courrier](https://bilans-ges.ademe.fr/forum/viewtopic.php?f=20&t=4192&sid=358e0c8fbbcd5a31cd145992fee0d60c)

- Les courts courriers ont un rayon d’action d’environ 500 kilomètres (ex : avions à hélices) : il s'agit de liaisons entre villes françaises (métropole) par exemple.
- Les moyens courriers ont un rayon d’action de 5000 kilomètres (Pour Air France, ils correspondent aux vols desservant l’Europe et l’Afrique du Nord). Exemple : A320.
- Les longs courriers sont des avions de ligne pouvant voler sur 15 000 kilomètres de distance. Il s'agit de vols transocéaniques par exemple. Exemple : A340.

Donc :
- 500 à 1 000 km : Court courrier
- 1 000 à 2 000 km : Moyen courrier
- 2 000 à 3 500 km : Moyen courrier
- au delà de 3 500 km : Long courrier

Qu'en penses-tu ?

**Comment by florianpanchout** [comment]
C'est en ligne !

**Comment by martinregner** [comment]
Possible de le répercuter aussi sur MIT ?

**Comment by florianpanchout** [comment]
Il va disparaitre dans une semaine non ?
