### ISSUE TITLE
Ajouter les valeurs (absolues et relatives) des ECV

### ISSUE THREAD

**Issue by florianpanchout** [datagir/monconvertisseurco2#117]

**Comment by florianpanchout** [comment]
Done. J'ai ajouté le détail sous forme de tableau. Je me dis que c'est le plus pratique qu'une infobulle pour manipuler les données

**Comment by martinregner** [comment]
Retour utilisateur : 

**Matières premières | 100,13 kg**

est compris comme "100 kg de matière première" ...
Pour lever tout soupçon, je propose de rajouter "kg CO2e"

**Comment by florianpanchout** [comment]
Done
