### ISSUE TITLE
Ajouter une licence libre

### ISSUE THREAD

**Issue by apitux** [datagir/monconvertisseurco2#118]
Merci et bravo pour ce travail.

Le site Datagir indique la possibilité de « librement partager, intégrer dans vos services, ou reprendre techniquement » ses simulateurs. 

Pour rendre effective cette permission, il faudrait leur apposer une licence libre.

**Comment by florianpanchout** [comment]
Bonjour,

Merci pour votre message. C'est maintenant [chose faite pour la licence](https://github.com/datagir/monconvertisseurco2/blob/master/license) :)
