### ISSUE TITLE
Version anglaise

### ISSUE THREAD

**Issue by Clemog** [datagir/monconvertisseurco2#123]
Retour de mail d'un réutilisateur qui souhaite traduire MIT :

> Pour les traductions, je peux les faire moi-même en anglais, espagnol et italien;
Je te propose de les faire gratuitement et de les mettre à disposition de vos utilisateurs pour une plus large connaissance;
Sinon, je pense qu'on peut peut-être les faire via l'API non ?

Quelle solution je peux lui proposer ?

- Reprendre le code et traduire de son coté ?
- Elle nous transmet ses traductions (MIT à priori) et on les mets en ligne (mais surement pas tout de suite) ?

Deuxième chose, d'un point de vue bizdev, je lui ai pour le moment conseillé MIT pour son besoin (itinéraire) mais j'aurais pu transmettre mcco2/transport, qu'en pensez vous ?

(ping @martinregner @Clem-mrtn)

**Comment by martinregner** [comment]
J'aurai tendance à plutôt favoriser le premier point. Pas vraiment identifié comme prioritaire de notre côté, et cela pose d'autres questions, notamment sur les FE.

En effet, si pour les modes thermiques les FE doivent être relativement proches dans les autres pays d'Europe, **ce n'est pas du tout le cas pour tous les modes élec.** Cela concerne une bonne partie des usages.
Dans la Base Carbone, il y a une partie d'entre eux (ex. train en Italie) mais pas tout.
Il faut qu'il ajoute un warning là-dessus, et n'associe pas l'ADEME comme pour NGC cf. §A de [Comment personnaliser Nos Gestes Climat pour vos besoins](https://github.com/datagir/nosgestesclimat-site/blob/master/PERSONNALISATION.md)

**Comment by Clemog** [comment]
Ok ça marche !

**Comment by Clem-mrtn** [comment]
Autre sollicitation pour le brésil cette fois ci: 

>Bonjour,
Je souhaiterais savoir s’il serait possible de disposer des informations disponibles en français sur ce site : https://monimpacttransport.fr/?theme=default, afin de les adapter à un contexte brésilien.
Je vous remercie sincèrement de votre retour et me tiens à votre disposition pour échanger,
Bien cordialement,

=> Je suis donc partie sur le même type de réponse
