### ISSUE TITLE
Phrase CTA sous les infographies à adapter pour certaines catégories

### ISSUE THREAD

**Issue by martinregner** [datagir/monconvertisseurco2#128]
Le CTA est "Voir tous les modes de transport" pour : 
- habillement
- chauffage

**Comment by florianpanchout** [comment]
Oups... c'est corrigé

**Comment by martinregner** [comment]
Pourquoi c'est différencié entre 

- habillement : "Voir plus d'équivalences" -> écran tuiles
- chauffage : "Voir tous les modes de chauffage" -> écran chauffage

**Comment by florianpanchout** [comment]
Parce que les infographies habillement montrent des équivalences avec d'autres catégories
