### ISSUE TITLE
Intégrer une catégorie "divers"

### ISSUE THREAD

**Issue by florianpanchout** [datagir/monconvertisseurco2#130]
Il y a des objets qui n'appartiennent à aucune catégorie mais qu'il serait quand même intéressant d'afficher sur le site. Est ce qu'une catégorie "divers" (avec un affichage sous forme de liste plutôt que de graph) serait une bonne idée ?

Exemple d'objets que l'on pourrait mettre dedans : 
- Livres
- Déchets 
- Cigarettes
- ...

**Comment by martinregner** [comment]
On ne va en effet pas pouvoir faire des dizaines de catégories.
L'inconvénient c'est juste leur comparaison sur un graphe en barres

Est-ce que le "Divers" ce n'est pas l'écran "CO2e" mais avec plus d'objets ou zoomé sur ces objets hors catégories ?

**Comment by florianpanchout** [comment]
Oui c'est un peu ce que j'avais en tête avec "(avec un affichage sous forme de liste plutôt que de graph)". Je pense quand même qu'il faut une page "https://monconvertisseurco2.fr/categories/divers" pour respecter l'architecture actuelle du site

**Comment by florianpanchout** [comment]
Première version [visible ici](https://divers--monconvertisseurco2.netlify.app/empreinte-carbone/divers)

**Comment by florianpanchout** [comment]
C'est en prod
