### ISSUE TITLE
Page Equivalent : barre d'affichage "Détail de l'empreinte"

### ISSUE THREAD

**Issue by Clem-mrtn** [datagir/monconvertisseurco2#133]
![image](https://user-images.githubusercontent.com/76995768/190167272-a021f7bd-a98c-4253-8130-c463cc619484.png)
Ce serait chouette sur cette barre par exemple qu'on puisse, en la survolant avoir le détail en KgCO2e de chaque item : 
- partie rouge x Kg de CO2e
- partie bleue x Kg de Co2e

**Comment by florianpanchout** [comment]
Déjà noté [ici](https://github.com/datagir/monconvertisseurco2/issues/117) :)
