### ISSUE TITLE
Impact Numérique

### ISSUE THREAD

**Issue by martinregner** [datagir/monconvertisseurco2#141]
**Lancement de la campagne :  11 janvier**

**Produit :**
- S'agissant d'un simulateur numérique, ajouter les comparaisons sur la fabrication des smartphone / ordi / télé au même niveau que les usages
- modifier les cases usages pour inclure des données d'usages : elles seraient pré-remplies avec les moyennes annuelles ou sur la vie d'un équipement façon MCC (hypothèse en attente) et pourraient être modifiées par l'utilisateur : ex. 256 mails, 129h de streaming ...
- Le fait de pré cocher un usage n'est pas forcément évident pour certains ; les cartes pourraient être triées par impact ?
- Préciser que l'utilisation du terminal lui-même est inclus dans les chiffres
- Ajouter :
  - Téléchargement/upload de fichier (en attente données)
  - Stockage de données dans le cloud (en attente données)
- Wording 
  - Streaming -> 1h de streaming (sauf si on peut faire varier le nombre d'heure)
  - Conférence -> 1h de conférence (sauf si on peut faire varier le nombre d'heure)
  - Préciser le poids de la PJ du mail 1Mo
  - emplacements --> participants

**Données :**
Toujours pas dispo… une réunion le 6/12 pour relancer

**Comment by Clem-mrtn** [comment]
#137
