### ISSUE TITLE
Expliciter la possibilité de supprimer des tuiles

### ISSUE THREAD

**Issue by guillett** [datagir/monconvertisseurco2#25]
Pour supprimer une tuile, il faut, pour le moment, appuyer sur le bouton + ; ce qui n'est pas évident :sweat_smile: 

![Screenshot_2021-02-02 Mon Convertisseur CO2e](https://user-images.githubusercontent.com/1410356/106570571-57c37a00-6536-11eb-9f3a-38b48fcba9de.png)

**Comment by florianpanchout** [comment]
@guillett Je ne suis pas sur que ça soit un parcours utilisateur réaliste.
Est ce que quelqu'un va arriver sur ce convertisseur et se dire "Oh, j'aimerais bien supprimer des options, mais surtout pas en ajouter ?"

**Comment by guillett** [comment]
Merci pour le retour, franchement quand j'insiste pour ne pas prendre la voiture pour me déplacer je passe pour un extrémiste.

J'ai rapidement partagé https://monconvertisseurco2.fr/?co2=0.605&equivalents=27976_206589 autour de moi pour expliquer ma posture. Je n'ai pas facilement compris que c'était possible (et encore moins sur mobile où il faut scroller pour voir le bouton).

**Comment by guillett** [comment]
Un autre intéressant selon moi https://monconvertisseurco2.fr/?co2=7.26&equivalents=20689_20688_20683

Je donne des cas où moi (en tant qu'usager) je suis content de savoir qu'on peut ajouter et supprimer des tuiles pour _make my point_.

**Comment by florianpanchout** [comment]
Intéressant comme utilisation. Ce qui pourrait être interessant ce serait de modifier l'UI de ce composant afin de pouvoir trier simplement par thématique.

**Comment by florianpanchout** [comment]
Traité via la v2
