### ISSUE TITLE
Ajouter des usages numérique

### ISSUE THREAD

**Issue by martinregner** [datagir/monconvertisseurco2#32]
Retour LinkedIn

Quand disponible dans la Base Carbone, ajouter des "_usages numériques en particulier le visionnage de vidéos en streaming_".

**Comment by florianpanchout** [comment]
Fait en prenant pour référence les valeurs trouvées ici : https://www.iea.org/commentaries/the-carbon-footprint-of-streaming-video-fact-checking-the-headlines

Ce sont les seules que j'ai trouvé qui prennent la production électrique de la France en compte

**Comment by florianpanchout** [comment]
Sera traité via Mon Impact Numérique

**Comment by martinregner** [comment]
C'est quoi que tu appelles "Mon Impact Numérique" ? c'est bien MonConvertisseurCO2.fr/Usage-numerique ? (snif, je vois que tu as dû le retirer)

**Comment by florianpanchout** [comment]
Soit ça, soit https://monimpactnumerique.netlify.app
