### ISSUE TITLE
Mettre + en évidence la fonctionnalité "inversée"

### ISSUE THREAD

**Issue by martinregner** [datagir/monconvertisseurco2#33]
Des retours utilisateurs (même aguerris) montrent qu'il n'apparait pas intuitif de modifier la valeur dans une carte pour que tout se recalcule autour.
(des stats sur le sujet ? :))

Sans doute déjà que laisser le cadre (pas seulement au survol) pourrait souligner la fonctionnalité ? autre idée ?

**Comment by florianpanchout** [comment]
Mieux ?

**Comment by martinregner** [comment]
Testons comme ça 👍
