### ISSUE TITLE
Scroll inutile sur les pop in

### ISSUE THREAD

**Issue by martinregner** [datagir/monconvertisseurco2#36]
![image](https://user-images.githubusercontent.com/46482115/119101309-21443900-ba19-11eb-93e3-01b07864fe40.png)

**Comment by martinregner** [comment]
idem sur les catégories dans le +
![image](https://user-images.githubusercontent.com/46482115/119690271-d035aa00-be49-11eb-8598-da0b6cff7e86.png)

**Comment by florianpanchout** [comment]
Corrigé
