### ISSUE TITLE
8 tonnes à perdre et pas 10

### ISSUE THREAD

**Issue by martinregner** [datagir/monconvertisseurco2#41]
Avec la màj des chiffres du CGDD, on est désormais à 10 tonnes par personnes et plus 12

Il faudrait donc remplacer le :
> 10 TONNES À PERDRE
> Aujourd'hui, un français émet en moyenne 12 tonnes de CO2e

...par :
> **8** TONNES À PERDRE
> Aujourd'hui, un français émet en moyenne **10** tonnes de CO2e

Je te laisse faire pour pas casser les anim ;)

**Comment by florianpanchout** [comment]
Done
