### ISSUE TITLE
Distinguer le nombre de carte par défaut entre site et embed

### ISSUE THREAD

**Issue by martinregner** [datagir/monconvertisseurco2#43]
Permettra d'afficher toutes les cartes sur le site sans rallonger l'iframe

**Comment by florianpanchout** [comment]
Il y a maintenant un paramètres defaultEmbed dans le json (pour l'instant sa valeur est identique à default)

**Comment by martinregner** [comment]
Top ! je viens de changer les données par défaut

**Comment by martinregner** [comment]
...mais ça change pas les données affichées 🤔 
J'ai fait une boulette @florianpanchout ?

**Comment by florianpanchout** [comment]
Tu as inversé default (les cartes qui s'affichent sur le site) et defaultEmbed (les cartes qui s'affichent en iframe) :)

**Comment by martinregner** [comment]
Ce qui a permis de tester dans l'autre sens comme ça 😄 
J'inverse 👍

**Comment by martinregner** [comment]
(et tout marche bien 👍 )
