### ISSUE TITLE
Refonte graphique 

### ISSUE THREAD

**Issue by Clem-mrtn** [datagir/monconvertisseurco2#44]
- [ ] Le choix des couleurs 
- [ ] Inversion bloc / équivalence tonnes de CO2e
- [ ] Les définitions du CO2e : trop complexe, surtout l’exemple 
- [ ] Remplir directement dans les cases les ordres de grandeur (surtout sur ordinateur) => peu intuitif
- [ ] En cliquant sur le (?) s’attend à avoir le FE unitaire
- [ ] Textes trop long et pas toujours clair 
       - 2 tonnes : « dommage de devoir scroller pour comprendre »
       - 8 tonnes à perdre : « je croyais que c’était la somme de toutes les tuiles »
- [ ] La pomme comme émoji pour le repas végé est confusant (kg de pommes)
- [ ] Le clic sur « notre configurateur » dans « comment intégrer… » ne remonte pas au configurateur

**Comment by florianpanchout** [comment]
Traité via #49
