### ISSUE TITLE
Retours figma 

### ISSUE THREAD

**Issue by Clem-mrtn** [datagir/monconvertisseurco2#49]
**Retours de l'atelier MCCO2 du 10.02 :** 

- Homepage  / affichage de l'iframe : page produit + vignettes de comparaison d'autres catégories. Sélection aléatoire / Type carroussel pour avoir divers produits qui s'affichent
- Rentrer dans le détail de la catégorie -comparaison  avec objets de la même catégorie 
- Possibilité de comparer plusieurs catégories entre elles 
- Rajouter l'unité Kg de CO2e 
- Rajouter une entrée pour convertir des chiffres en objet tangible du quotidien (cibles : collectivité, comex etc. qui veulent traduire des chiffres.) 
- Pousser la page catégorie numérique comme " v1 du simulateur Mon Impact Numérique"
- Mise en place d'une API  

Questions : 
- Garde t-on initialement la page d'accueil avec toutes les catégories sous forme de vignette ?

**Comment by florianpanchout** [comment]
Une version avec la nouvelle home "Équivalents / Catégories" : https://www.figma.com/proto/8cDevHNLXyq6K1At3gGZh9/Mon-Convertisseur-CO2?page-id=349%3A4805&node-id=349%3A5278&viewport=331%2C48%2C1&scaling=scale-down

**Comment by martinregner** [comment]
C'est top !

L'entrée directe de kg de CO2 ce serait l'une des cartes du slider ?

**Comment by florianpanchout** [comment]
Une version en cours de dev visible ici : https://mcc-v2.netlify.app/

**Comment by Clem-mrtn** [comment]
- Afficher l'arborescence pour permettre à l'utilisateur une fois rentrer dans le détails de naviguer facilement entre les pages 
- Rubrique "Poids" <=> wording ? A voir ce que l'on affiche et comment ? 
- Catégorie Mobilier : livre de poches ? Compléter avec l'étude Impact

**Comment by martinregner** [comment]
> Rubrique "Poids" <=> wording ? A voir ce que l'on affiche et comment ?

"tonne ou kg CO2e" ?
