### ISSUE TITLE
Wording 

### ISSUE THREAD

**Issue by florianpanchout** [datagir/monconvertisseurco2#51]
J'ai beaucoup de mal à trouver des noms pertinents pour les catégories ("Équivalents", "Catégories" et "Poids") et pour les CTA ("Voir le détail").

Si vous avez mieux, je suis preneur

**Comment by Clem-mrtn** [comment]
Je réfléchissais pour le coup je trouvais que : 
- Equivalents 
- Catégories 
- Voir le détail
c'était assez parlant => à tester par des users à la v1 

Par contre pour "Poids" je suis d'accord ce n'est pas très clair... 
Mes propositions (des premières idées) : 
- Convertir 
- Conversion 
- Kg / Tonnes

**Comment by martinregner** [comment]
> - Equivalents
> - Catégories

pareil, ça me parait clair, à tester.


Pour "Poids", je trouve pour rester cohérent avec le reste, je mettrait bien "kgCO2" ou "conversion kgCO2" (bon, c'est un peu le titre du site ! ^^)
