### ISSUE TITLE
Équivalents par défaut (slider et tuiles)

### ISSUE THREAD

**Issue by florianpanchout** [datagir/monconvertisseurco2#53]
Vous avez une idée des équivalents à afficher dans le slider et ceux à mettre par défaut dans la liste de tuiles ?

J'ai pris le parti de ne mettre que des objets dans le slider (plus simple à comprendre que les équivalents en km ou en litres), et à ne pas les afficher en dessous (pour que la liste de tuile reste fixe)

**Comment by Clem-mrtn** [comment]
**Pour le slider : **
Je trouve ça plutôt bien comme ça, c'est une bonne idée de mettre des objets dans le slider je partage que c'est effectivement plus parlant que des KM de voitures pour créer des comparaisons. D'autant + si l'usager rentre par des recherches google, ça a + de sens ! 

Une idée toutefois serait, peut-être dans une v2 de pouvoir arriver sur des équivalents qu'on aurait recherché depuis un autre de nos simulateurs.
Ex : Je simule l'impact de ma mobilité. Je veux comprendre ce que représente les 150 Kg de CO2e de mes X Km de voiture, je clique sur un cross lien depuis MIT et j'arrive sur cet "équivalent" par défaut ou alors sur l'onglet "Poids" 

**Pour les tuiles :**  
Y a des items très spécifiques qui ne me parlent pas tellement : chaise, canapé convertible, jet d'imprimante, lit...
Aussi je trouve que ce n'est pas très parlant quand on est en dessous des 0 =>  *"0.9 de manteaux"* Ca veut dire quoi ?
Peut-être le retirer par défaut quand on est dessous de 1 ? 
**Pareil réflexion : puisqu'on est sur des **ordres de grandeur**, est-ce qu'on garde les décimales ?**

**Comment by florianpanchout** [comment]
Une première version de la visualisation emoji est visible ici : https://mcc-v2.netlify.app/

Je n'affiche pas encore les fraction d'emoji

Honnêtement, c'est joli sur une infographie, mais ici j'ai du mal à voir ce que ça apporte. J'ai même l'impression que ça renvoie le mauvais message sur le nombre de km en voiture

**Comment by martinregner** [comment]
> J'ai même l'impression que ça renvoie le mauvais message sur le nombre de km en voiture

Oui en particulier s'il y a une division par 10.
Peut-être laisser l'utilisateur choisir de diviser par 10 ou non, par ex avec une case à cocher ou un petit bouton à slider ?
Ou sinon ajouter un "10 x" en gros au milieu des émojis ?

**Comment by Clem-mrtn** [comment]
Je suis un peu perplexe de cet écran... 
Afficher des emojis pour mieux illustrer les équivalences et avoir quelque chose de plus visuel je trouve ça bien mais je trouve le message pas très clair avec les voitures

Que ce soit pour le ratio (1 pour 10km) ou même si on mettait la totalité : ça fait un peu "brouillon" ce n'est pas très lisible ni très esthétique
**=>  Mettre  quelques voitures et un autres emoji pour illustrer l'impact ? : une route ? Une multiplication ? Trois petits points... ?**
**=>N'afficher que quelques voitures et mettre une flèche pour déplier l'intégralité ?** 

Autre sujet pour moi : on a beaucoup beaucoup d'objets dans le slider... Cela ne rend pas facile la navigation si on veut revenir à un objet particulier
=> en mettre que quelques uns par défaut et je sais pas en rajouter avec un + ?

**Comment by florianpanchout** [comment]
> Autre sujet pour moi : on a beaucoup beaucoup d'objets dans le slider... Cela ne rend pas facile la navigation si on veut revenir à un objet particulier

Yes, ça rejoint mon premier message : je ne sais pas quels équivalents sont pertinents à afficher dans le slider
