### ISSUE TITLE
Affichage cartes - Catégories 

### ISSUE THREAD

**Issue by Clem-mrtn** [datagir/monconvertisseurco2#55]
Dans la partie des équivalences on a beaucoup beaucoup de petites cartes : est-ce qu'on ne ferait pas comme ce qui existe déjà aujourd'hui dans la version actuelle : on mettrait un "+" pour rajouter des objets ?

**Comment by florianpanchout** [comment]
Est ce que c'est un problème ? Il n'y a rien en dessous et on a eu comme retour sur la dernière version que les gens voulaient tout voir d'un coup

**Comment by martinregner** [comment]
Le fait qu'il y en ait beaucoup me perd aussi.
Il faudrait au moins une barre d'avancement pour savoir où on en est dans le défilement, pour les cartes du haut comme du bas.

Pour celle du haut, il y a p-e pas besoin d'autant (difficile de savoir où on en est dans la navigation, de revenir à une carte en particulier sans tâtonner un peu...)

**Comment by florianpanchout** [comment]
My bad, je pensais que l'on parlait de cette page : https://mcc-v2.netlify.app/co2
