### ISSUE TITLE
Infographies

### ISSUE THREAD

**Issue by florianpanchout** [datagir/monconvertisseurco2#56]
(suite de https://github.com/datagir/monconvertisseurco2/issues/53)

>Je suis un peu perplexe de cet écran...
Afficher des emojis pour mieux illustrer les équivalences et avoir quelque chose de plus visuel je trouve ça bien mais je trouve le message pas très clair avec les voitures

Est ce que cet écran ne pourrait pas être juste des équivalences "toutes faites" ? Ce ne serait plus un simulateur interactif mais une liste d'infographie. Ça nous permettrait d'avoir un bien meilleur contrôle de la pertinence de ce que l'on affiche et d'en rajouter au fur et à mesure.

Dans tous les cas, je propose en attendant de mettre l'écran "Catégories" par défaut à la place de celui ci.

**Comment by Clem-mrtn** [comment]
INFOGRAPHIES 😻

**Comment by Clem-mrtn** [comment]
> Dans tous les cas, je propose en attendant de mettre l'écran "Catégories" par défaut à la place de celui ci. 

Je partage, afin de mettre en place une action concrète 👍 .
Quitte à désactiver l'écran "Equivalences" le temps de statuer et de mettre en ligne cette première version. (une fois que les données de Pierre sont bonnes...)

**Comment by martinregner** [comment]
Carrément ! 👍 👍 
C'était bien l'idée de cet écran : proposer des choses visuelles style infographie. On peut tout à fait les construire nous-mêmes (dans un premier temps, ou pas) !

Avec une fonction partage de l'infographie (avec source .... et l'url du simulateur dessus bien sûr ;)

**Comment by florianpanchout** [comment]
J'ai fait une demande de rdv auprès de l'équipe des designers transverses

**Comment by florianpanchout** [comment]
Suite de #60 

Quelques idées d'infographie supplémentaires qui pourraient être intéressantes :

Impact vêtement / consommation d'eau. Ex : un Jean équivaut à 53 bouteilles d'eau équivaut à une grosse goutte d'eau du robinet

Impact alcool / eau. Ex : 1 Litre de vin / bière équivaut à 3 litres d'eau bouteille équivaut à une grosse goutte d'eau du robinet

Impact poisson gras / poisson blanc / viandes (notamment pour aller dans le sens que de manger du saumon tous les jours pas ouf)

**Comment by florianpanchout** [comment]
Traité via #64
