### ISSUE TITLE
Retours Figma v2 

### ISSUE THREAD

**Issue by Clem-mrtn** [datagir/monconvertisseurco2#60]
- [ ] Barre de recherche : quand on tape un objet qui n'est pas dans la base rien ne se passe. Peut-être permettre de cliquer sur "entrer" et afficher un message d'erreur 
**_Ex : Recherche ipad => "cet objet n'est pas dans la base. Retrouvez l'impact des objets de la catégories Numériques"_** 
Aussi l'auto-remplissage bug un peu 
**_Ex : Télévision - aux première lettres il m'affiche manteau, canapé textile etc._** 
![image](https://user-images.githubusercontent.com/76995768/166455454-455221ab-313c-47d3-aa80-3184e03cb51a.png)

- [ ] Emojis : Pour les objets dont on a pas forcément d'emoji adéquate, tenter de se rapprocher de la description
_**Ex : Table en bois - est-ce qu'on a un emoji bois plutôt qu'un carton ?**_ 
C'est un détail mais je me dis 
- [ ] Ce serait pas mal aussi de mettre un bouton **"Partager"**  sur les infographies, pour permettre aux utilisateurs de ne partager que l'image sur les RS par ex 
- [ ] Quelques idées d'infographie supplémentaires qui pourraient être intéressantes : 
- Impact vêtement / consommation d'eau. **_Ex : un Jean équivaut à 53 bouteilles d'eau équivaut à une grosse goutte d'eau du robinet_** 
- Impact alcool / eau. _**Ex : 1 Litre de vin / bière équivaut à 3 litres d'eau bouteille équivaut à une grosse goutte d'eau du robinet**_
- Impact poisson gras / poisson blanc / viandes (notamment pour aller dans le sens que de manger du saumon tous les jours pas ouf) 
- Et après on pourra en créer d'autres au fur et à mesure 
- [ ] Il faudrait remplacer la vignette de MCCO2 (je sais + si on parle de métatag ?) pour afficher la nouvelle version lors du partage sur les RS + nouveau texte (l'ancien texte n'est p-t + adapté)
- [ ] Juste une réflexion que je me faisais : pour la catégorie "**Déplacements**" c'est vraiment Mon Impact Transport... On se retrouve un peu avec un doublon entre les deux simulateurs. 
Aussi dans cette version on ne prend toujours pas encore l'impact de la fabrication c'est ça ? 
- [ ] Partie Intégration : on parle de widget. Juste cohérence avec les autres sites ou ne parle que de "simulateurs" (à intégrer en iframe) ?

**Comment by florianpanchout** [comment]
Issues créé (ou réouvertes) pour chacun des sujets sauf : 

>  Il faudrait remplacer la vignette de MCCO2 (je sais + si on parle de métatag ?) pour afficher la nouvelle version lors du partage sur les RS + nouveau texte (l'ancien texte n'est p-t + adapté)

La nouvelle meta s'affichera lorsque l'on mettra le simulateur en production

>  Partie Intégration : on parle de widget. Juste cohérence avec les autres sites ou ne parle que de "simulateurs" (à intégrer en iframe) ?

C'est une page en cours de développement. Personne ne la verra sauf nous
