### ISSUE TITLE
Barre de recherche

### ISSUE THREAD

**Issue by florianpanchout** [datagir/monconvertisseurco2#61]
Suite de #60 

Quand on tape un objet qui n'est pas dans la base rien ne se passe. Peut-être permettre de cliquer sur "entrer" et afficher un message d'erreur
Ex : Recherche ipad => "cet objet n'est pas dans la base. Retrouvez l'impact des objets de la catégories Numériques"
Aussi l'auto-remplissage bug un peu
Ex : Télévision - aux première lettres il m'affiche manteau, canapé textile etc.

**Comment by florianpanchout** [comment]
Il serait intéressant d'avoir une liste de synonymes comme sur QFDMD afin que la recherche soit plus efficace.

Aussi on intégre qu'une partie des objets de l'étude (pour que les catégories ne soient pas trop longue). Peut être intégrer le reste des objets afin que le site soit plus exhaustif ?

("Retrouvez l'impact des objets de la catégories Numériques" => c'est compliqué de savoir que l'objet appartient à la catégorie Numérique s'il n'est pas dans la base)

**Comment by martinregner** [comment]
Je propose de retirer la barre de recherche (pas indispensable si ?) à la release pour faire ces améliorations (plutôt utiles en effet) dans un deuxième temps.
Qu'en pensez-vous?

**Comment by Clem-mrtn** [comment]
> En dehors de trouver la liste de synonymes, le reste ne prends pas énormément de temps.

T'entends quoi comme synonyme ?

> Aussi on intégre qu'une partie des objets de l'étude (pour que les catégories ne soient pas trop longue). Peut être intégrer le reste des objets afin que le site soit plus exhaustif ? 

De tout intégrer ça demande pas mal de temps de mise en forme non ? 

En attendant on peut laisser la barre et pour l'instant mettre un message "d'erreur"

**Comment by florianpanchout** [comment]
> T'entends quoi comme synonyme ?

Une liste de synonymes qui permettraient de tomber plus facilement sur les équivalents. Ça permettrais par exemple de taper "Macbook" et que l'on propose "Ordinateur portable"

> De tout intégrer ça demande pas mal de temps de mise en forme non ?

Ça demande du temps pour entrer les données, mais c'est de l'ordre de la journée

**Comment by martinregner** [comment]
Très bien le message "pas trouvé" pour le moment, et qui propose de parcourir les catégories pour trouver un objet équivalent.

**Comment by florianpanchout** [comment]
Un message s'affiche maintenant avec la liste des catégories
