### ISSUE TITLE
Préciser les sources et les rendre cliquables

### ISSUE THREAD

**Issue by martinregner** [datagir/monconvertisseurco2#66]
Rendre les sources cliquables (ex. vers Agribalyse ou NGC) et les préciser.
Je peux t'aider dans ces modifications bien sûr

**Comment by florianpanchout** [comment]
Les sources sont maintenant cliquables. Dans un second temps il serait intéressant de reprendre le contenu de ces sources (hypothèses et calculs) pour étoffer le contenu texte des pages équivalents
