### ISSUE TITLE
Accessibilité mode sombre

### ISSUE THREAD

**Issue by martinregner** [datagir/monconvertisseurco2#67]
Les flèches et textes en surbrillance ne sont pas très visibles / lisibles

![image](https://user-images.githubusercontent.com/46482115/166492540-d13ae095-95f6-4757-8ceb-d2c38d4db0a3.png)

Idem pour les lignes non sélectionnées dans la section "+"
![image](https://user-images.githubusercontent.com/46482115/166495678-3d77d1cb-73d9-4a30-a32c-ca973fc37756.png)

**Comment by florianpanchout** [comment]
Corrigé
