### ISSUE TITLE
Comprendre le CO2e

### ISSUE THREAD

**Issue by martinregner** [datagir/monconvertisseurco2#68]
Tu pensais mettre quoi au clic, le petit texte de la précédente version ?

> **L'équivalent CO2 (CO2e)**
> Le dérèglement climatique actuel est une conséquence de nos émissions importantes de gaz à effet de serre. Nous avons la chance de pouvoir mesurer ces émissions avec un indice simple : les kilogrammes d'équivalent CO2 (kgCO2e).
> 
> Par exemple, 1 kg de méthane équivaut à 28 kg de CO2. Si la fabrication d'un produit a émis 1 kg de méthane et 1 kg de CO2, alors l'impact total de ce produit est de 29 kg d'équivalent CO2.

**Comment by florianpanchout** [comment]
J'imaginais une page avec une description un peu plus poussée avec des infographies (®) et tout.

Mais probablement juste ce texte la dans un premier temps oui

**Comment by florianpanchout** [comment]
Done
