### ISSUE TITLE
🐛 Changement de catégorie via les flèches

### ISSUE THREAD

**Issue by martinregner** [datagir/monconvertisseurco2#69]
![image](https://user-images.githubusercontent.com/46482115/166493791-8bda6314-e1d9-4330-87cb-563fa57193d2.png)

En changeant de catégorie via les flèches, il semblerait que la barre verte avec le nom de la catégorie disparaisse puis réapparaisse (qq dixièmes de sec) après le changement de nom (avec le nom de la nouvelle catégorie).
Cela fait un petit "flash" blanc à la disparition / réapparition de la barre

**Comment by florianpanchout** [comment]
Corrigé
