### ISSUE TITLE
Comptabiliser utilisation et fin de vie ?

### ISSUE THREAD

**Issue by florianpanchout** [datagir/monconvertisseurco2#70]
La Base Carbone ne comptabilise pas l'utilisation et la fin de vie. L'étude `Modélisation et évaluation des impacts environnementaux de produits de consommation et biens d'équipement` fournie ces données.

Est ce qu'on veut afficher ces deux étapes ? Personnellement j'ai l'impression que ça complexifie la compréhension des données et, comme la Base Carbone, je ne l'ajouterais pas dans le total. La valeur donnée est pour moi plus simple à comprendre comme valeur "à l'achat", le reste dépendant de moi.

Par contre ce serait intéressant de laisser la possibilité de configurer la durée d'utilisation et la fin de vie du produit afin que les utilisateurs puissent se rendre compte de l'impact de l'utilisation et du recyclage

**Comment by Clem-mrtn** [comment]
> L'utilisation

Tu entends l'usage ? Le poids du stream sur un ordi portable etc. (donnée de méga octet) ?

> Par contre ce serait intéressant de laisser la possibilité de configurer la durée d'utilisation et la fin de vie du produit afin que les utilisateurs puissent se rendre compte de l'impact de l'utilisation et du recyclage

Oui je suis d'accord dans une prochaine version on pourrait permettre aux gens de faire cette simulation pour passer des messages sur "garder son téléphone longtemps" & oui le recycler ou le revendre ? (seconde main ?)

**Comment by Clemog** [comment]
On parle seulement du numérique pour cette issue ?

**Comment by florianpanchout** [comment]
Nope, tous les objets (sauf repas / transports) sont concernés

**Comment by florianpanchout** [comment]
Done
