### ISSUE TITLE
Ajouter un lien vers /CO2e dans les fiches produits

### ISSUE THREAD

**Issue by Clemog** [datagir/monconvertisseurco2#71]
Je pense que ce serait pas mal d'ajouter un lien vers /CO2e sur les fiches produit au niveau de 

" 1 xxxxx
c’est autant d’émissions que pour
fabriquer, consommer ou parcourir :"

Je sens que lorsque on arrive ici, on peut se demander ou est la viz tuiles ou on peut changer l'objet/la valeur de référence

**Comment by florianpanchout** [comment]
Traité via https://github.com/datagir/monconvertisseurco2/issues/74
