### ISSUE TITLE
Case "voir tous les équivalents"

### ISSUE THREAD

**Issue by Clem-mrtn** [datagir/monconvertisseurco2#75]
La checkbox _"voir tous les équivalents"_ permet de voir plus d'items pour seulement les catégories : 
- Electroménager
- Numérique 

=> Elle pourrait ne pas apparaître pour les categs non concernées puisque sinon quand on clic dessus rien ne se passe ?

**Comment by florianpanchout** [comment]
Done. Elle ne s'affiche plus pour les repas et chaque autre catégorie a des items cachés par défaut
