### ISSUE TITLE
Fav Icon MCCO2 

### ISSUE THREAD

**Issue by Clem-mrtn** [datagir/monconvertisseurco2#90]
![image](https://user-images.githubusercontent.com/76995768/173537535-1cff84a0-59fd-48c1-9cd5-8d2fcfdba2fb.png)

En prod (onglet de droite) j'ai toujours l'ancien fav icon, même en vidant mon cache, alors qu'en staging j'ai le bon (onglet de gauche)
Suis-je encore la seule ? 😅

**Comment by florianpanchout** [comment]
J'imagine un problème de cache ? Est ce que tu as le problème en navigation privée ?

**Comment by Clem-mrtn** [comment]
Je te confirme 
![image](https://user-images.githubusercontent.com/76995768/173766744-fa2a6da2-2de2-40b2-9391-9e5ebd421f06.png)

Et je te confirme que j'ai vidé mon cache une bonne dizaine de fois
T'as le bon fav icon ?

**Comment by florianpanchout** [comment]
Et maintenant ? J'ai modifié le nom de l'image

(j'ai le bon favicon mais c'est peut être moi qui ai un problème de cache...)

**Comment by Clem-mrtn** [comment]
C'est bon :)
