### ISSUE TITLE
"Ajouter un équivalent" : doublon dans la liste

### ISSUE THREAD

**Issue by Clem-mrtn** [datagir/monconvertisseurco2#95]
Il y a quelques doublons dans la liste des mosaïques : 

- Litre de lait 
- Canapé 
- Ordinateur fixe (3x)
- Tablette 
- Appareil photo

**Comment by florianpanchout** [comment]
Corrigé. J'affiche maintenant les sous-titres dans la liste

**Comment by Clem-mrtn** [comment]
Ok + clair 👍 
Merci !
