### ISSUE TITLE
Partage twitter -> "title" étrange

### ISSUE THREAD

**Issue by laem** [datagir/monconvertisseurco2#97]
"title https://monconvertisseurco2.fr/categories/numerique"

Aussi, ça me semble intéressant d'y attacher un mot dièse genre #monconvertisseurco2

**Comment by florianpanchout** [comment]
Corrigé. J'ai mis le titre du simulateur en message par défaut ("Découvrez l’impact sur le climat des objets et gestes de votre quotidien") et ajouté un hashtage #monconvertisseurco2 pour Twitter

**Comment by laem** [comment]
Tu l'as testé ici ? https://cards-dev.twitter.com/validator
